version: "3.9"

services:
  go-temporal-mongodb:
    image: mongo:5.0
    container_name: go-temporal-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - go-mongodb_data:/data/db
  go-temporal-elasticsearch:
    container_name: go-temporal-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms100m -Xmx100m
    image: elasticsearch:7.10.1
    networks:
      - go-temporal-network
    ports:
      - 9200:9200
  go-temporal-postgresql:
    container_name: go-temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:9.6
    networks:
      - go-temporal-network
    ports:
      - 5432:5432
  go-temporal:
    container_name: go-temporal
    depends_on:
      - go-temporal-postgresql
      - go-temporal-elasticsearch
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=go-temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development_es.yaml
      - ENABLE_ES=true
      - ES_SEEDS=go-temporal-elasticsearch
      - ES_VERSION=v7
    image: temporalio/auto-setup:1.13.0
    networks:
      - go-temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  go-temporal-admin-tools:
    container_name: go-temporal-admin-tools
    depends_on:
      - go-temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=go-temporal:7233
    image: temporalio/admin-tools:1.13.0
    networks:
      - go-temporal-network
    stdin_open: true
    tty: true
  go-temporal-web:
    container_name: go-temporal-web
    depends_on:
      - go-temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=go-temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.13.0
    networks:
      - go-temporal-network
    ports:
      - 8088:8088

networks:
  go-temporal-network:
    driver: bridge
    name: go-temporal-network

volumes:
  go-mongodb_data:
